# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './sumtool/ui/uimain.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(687, 434)
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(Dialog)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(20, 380, 225, 41))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.aboutButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        self.aboutButton.setObjectName("aboutButton")
        self.horizontalLayout_4.addWidget(self.aboutButton)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(20, 40, 281, 21))
        self.label.setObjectName("label")
        self.openFileButton = QtWidgets.QPushButton(Dialog)
        self.openFileButton.setGeometry(QtCore.QRect(520, 30, 111, 31))
        self.openFileButton.setObjectName("openFileButton")
        self.lineEdit_SelectFile = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_SelectFile.setGeometry(QtCore.QRect(20, 70, 611, 33))
        self.lineEdit_SelectFile.setObjectName("lineEdit_SelectFile")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(20, 170, 161, 21))
        self.label_2.setObjectName("label_2")
        self.lineEdit_ChecksumValue = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_ChecksumValue.setGeometry(QtCore.QRect(20, 200, 541, 33))
        self.lineEdit_ChecksumValue.setObjectName("lineEdit_ChecksumValue")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(20, 300, 161, 21))
        self.label_3.setObjectName("label_3")
        self.lineEdit_ChecksumCmp = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_ChecksumCmp.setGeometry(QtCore.QRect(20, 330, 541, 31))
        self.lineEdit_ChecksumCmp.setObjectName("lineEdit_ChecksumCmp")
        self.horizontalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 250, 611, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label_Result = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(19)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label_Result.setFont(font)
        self.label_Result.setText("")
        self.label_Result.setObjectName("label_Result")
        self.horizontalLayout.addWidget(self.label_Result)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.closeButton = QtWidgets.QPushButton(Dialog)
        self.closeButton.setGeometry(QtCore.QRect(520, 390, 111, 31))
        self.closeButton.setObjectName("closeButton")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(Dialog)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(20, 110, 371, 51))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.lineEdit_FileSize = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.lineEdit_FileSize.setObjectName("lineEdit_FileSize")
        self.horizontalLayout_2.addWidget(self.lineEdit_FileSize)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(Dialog)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(400, 110, 231, 51))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.progressBarChecksum = QtWidgets.QProgressBar(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.progressBarChecksum.setFont(font)
        self.progressBarChecksum.setProperty("value", 24)
        self.progressBarChecksum.setObjectName("progressBarChecksum")
        self.horizontalLayout_3.addWidget(self.progressBarChecksum)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "checksum-gui"))
        self.aboutButton.setText(_translate("Dialog", "A propos de checksum-gui"))
        self.label.setText(_translate("Dialog", "Select file to compute MD5 checksum:"))
        self.openFileButton.setText(_translate("Dialog", "Browser"))
        self.label_2.setText(_translate("Dialog", "MD5 checksum Value:"))
        self.label_3.setText(_translate("Dialog", "Compare MD5-Value:"))
        self.closeButton.setText(_translate("Dialog", "Close"))
        self.label_4.setText(_translate("Dialog", "File size:"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
